# Generated by Django 3.2 on 2021-12-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecoords',
            name='address',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Адрес места'),
        ),
        migrations.AlterField(
            model_name='placecoords',
            name='date_of_calculate_coords',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата получения координат места'),
        ),
    ]
