# Generated by Django 3.2 on 2021-12-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0003_alter_placecoords_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecoords',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='placecoords',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
