# Generated by Django 3.2 on 2021-12-12 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0004_auto_20211203_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecoords',
            name='date_of_calculate_coords',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Дата получения координат места'),
            preserve_default=False,
        ),
    ]
