# Generated by Django 3.2 on 2021-11-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20211115_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comments',
        ),
    ]
