# Generated by Django 3.2 on 2021-11-21 06:47

from django.db import migrations


def calculate_orders_cost(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    order_items = OrderItem.objects.all()
    for order_item in order_items.iterator():
        if not order_item.cost:
            order_item.cost = order_item.product.price * order_item.cost
            order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20211121_0641'),
    ]

    operations = [
        migrations.RunPython(calculate_orders_cost),
    ]
