# Generated by Django 3.2 on 2021-11-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20211121_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Необработанный'), ('CLOSED', 'Обработанный')], default='OPEN', max_length=200, verbose_name='Статус'),
        ),
    ]
