# Generated by Django 3.2 on 2021-11-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20211125_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('OFFLINE', 'Наличными'), ('ONLINE', 'Онлайн')], default='OFFLINE', max_length=200, verbose_name='Способ оплаты'),
        ),
    ]
