# Generated by Django 3.2 on 2021-11-27 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_alter_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='available_restaurants',
            field=models.ManyToManyField(blank=True, to='foodcartapp.Restaurant', verbose_name='Доступные рестораны'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='Выбранный ресторан'),
        ),
    ]
