# Generated by Django 3.2 on 2021-12-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20211127_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('OFFLINE', 'Наличными'), ('ONLINE', 'Онлайн')], default='OFFLINE', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Необработанный'), ('CLOSED', 'Обработанный')], default='OPEN', max_length=20, verbose_name='Статус'),
        ),
    ]
