# Generated by Django 3.2 on 2021-12-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_alter_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('OFFLINE', 'Наличными'), ('ONLINE', 'Онлайн'), ('UNDEFINED', 'Нужно уточнить')], default='UNDEFINED', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
